branch-defaults:
  main:
    environment: your-frontend-env-name
    group_suffix: null

global:
  application_name: your-app-name
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 18
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
  environment_type: SingleInstance
  solution_stack_name: 64bit Amazon Linux 2 v5.8.0 running Node.js 18 